server:
  port: 2000

spring:
  application:
    name: mysql-data-service
  redis:
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:16379
    database: 1
    timeout: 3000
  datasource:
    master:
      name: test
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/scadadata?serverTimezone=Asia/Shanghai
      username: root
      password: root
    slave:
      name: test
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3307/scadadata?serverTimezone=Asia/Shanghai
      username: root
      password: root
    hikari:
      maximum-pool-size: 20
      auto-commit: true
      max-lifetime: 5000
      connection-timeout: 1000



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    hostname: localhost


logging:
  file:
    path: /log
    name: Mysql_data.log
  level:
    com:
      example:
        DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


